<a href="https://colab.research.google.com/github/NWemphy/MachineLearningB_/blob/main/Pertemuan_2_Preprosesing_Gaji_225314043.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np



In [2]:
df = pd.read_excel('gaji_225314043.xlsx')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   NEGARA  10 non-null     object 
 1   USIA    9 non-null      float64
 2   GAJI    9 non-null      float64
 3   BELI    10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [3]:
df=df.copy()
df

NEGARA  USIA     GAJI BELI
0   FRANCE  44.0  58000.0   NO
1    SPAIN  27.0  48000.0  YES
2  GERMANY   NaN  64000.0   NO
3    SPAIN  35.0  62000.0  YES
4  GERMANY  40.0  54000.0  YES
5   FRANCE  35.0      NaN  YES
6    SPAIN  38.0  52000.0   NO
7   FRANCE  48.0  79000.0  YES
8  GERMANY  55.0  83000.0   NO
9   FRANCE  32.0  68000.0  YES

In [4]:
df['USIA'] = df['USIA'].fillna(df['USIA'].mean())
df.head()

NEGARA       USIA     GAJI BELI
0   FRANCE  44.000000  58000.0   NO
1    SPAIN  27.000000  48000.0  YES
2  GERMANY  39.333333  64000.0   NO
3    SPAIN  35.000000  62000.0  YES
4  GERMANY  40.000000  54000.0  YES

In [5]:
df['GAJI']=df['GAJI'].fillna(df['GAJI'].mean())
df.tail()


NEGARA  USIA          GAJI BELI
5   FRANCE  35.0  63111.111111  YES
6    SPAIN  38.0  52000.000000   NO
7   FRANCE  48.0  79000.000000  YES
8  GERMANY  55.0  83000.000000   NO
9   FRANCE  32.0  68000.000000  YES

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   NEGARA  10 non-null     object 
 1   USIA    10 non-null     float64
 2   GAJI    10 non-null     float64
 3   BELI    10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [7]:
df.drop("NEGARA", axis=1,inplace=True)
df.drop("BELI", axis=1,inplace=True)


In [8]:
df

USIA          GAJI
0  44.000000  58000.000000
1  27.000000  48000.000000
2  39.333333  64000.000000
3  35.000000  62000.000000
4  40.000000  54000.000000
5  35.000000  63111.111111
6  38.000000  52000.000000
7  48.000000  79000.000000
8  55.000000  83000.000000
9  32.000000  68000.000000

In [9]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
score_df = ss.fit_transform(df)

In [10]:
score_df

array([[ 0.60858062, -0.47977614],
       [-1.60839164, -1.4184686 ],
       [ 0.        ,  0.08343933],
       [-0.56511058, -0.10429916],
       [ 0.08694009, -0.85525313],
       [-0.56511058,  0.        ],
       [-0.17388018, -1.04299162],
       [ 1.13022115,  1.49147801],
       [ 2.04309208,  1.866955  ],
       [-0.95634097,  0.45891631]])

In [11]:
df_zscore=pd.DataFrame(score_df,columns=['ZSCORE USIA','ZSCORE GAJI'])
df_zscore

ZSCORE USIA  ZSCORE GAJI
0     0.608581    -0.479776
1    -1.608392    -1.418469
2     0.000000     0.083439
3    -0.565111    -0.104299
4     0.086940    -0.855253
5    -0.565111     0.000000
6    -0.173880    -1.042992
7     1.130221     1.491478
8     2.043092     1.866955
9    -0.956341     0.458916

In [12]:
from sklearn.preprocessing import MinMaxScaler

sclaer = MinMaxScaler()
x_minmax = sclaer.fit_transform(df)

In [13]:
x_minmax

array([[0.60714286, 0.28571429],
       [0.        , 0.        ],
       [0.44047619, 0.45714286],
       [0.28571429, 0.4       ],
       [0.46428571, 0.17142857],
       [0.28571429, 0.43174603],
       [0.39285714, 0.11428571],
       [0.75      , 0.88571429],
       [1.        , 1.        ],
       [0.17857143, 0.57142857]])

In [14]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(1,10))
min_max10 = scaler.fit_transform(df)
min_max10

array([[ 6.46428571,  3.57142857],
       [ 1.        ,  1.        ],
       [ 4.96428571,  5.11428571],
       [ 3.57142857,  4.6       ],
       [ 5.17857143,  2.54285714],
       [ 3.57142857,  4.88571429],
       [ 4.53571429,  2.02857143],
       [ 7.75      ,  8.97142857],
       [10.        , 10.        ],
       [ 2.60714286,  6.14285714]])

In [15]:
df_minmax10 = pd.DataFrame(min_max10,columns=['MinMax 10 USIA','MinMax 10 GAJI'])
df_minmax10

MinMax 10 USIA  MinMax 10 GAJI
0        6.464286        3.571429
1        1.000000        1.000000
2        4.964286        5.114286
3        3.571429        4.600000
4        5.178571        2.542857
5        3.571429        4.885714
6        4.535714        2.028571
7        7.750000        8.971429
8       10.000000       10.000000
9        2.607143        6.142857

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
min_max0 = scaler.fit_transform(df)
min_max0

array([[0.60714286, 0.28571429],
       [0.        , 0.        ],
       [0.44047619, 0.45714286],
       [0.28571429, 0.4       ],
       [0.46428571, 0.17142857],
       [0.28571429, 0.43174603],
       [0.39285714, 0.11428571],
       [0.75      , 0.88571429],
       [1.        , 1.        ],
       [0.17857143, 0.57142857]])

In [17]:
df_minmax0 = pd.DataFrame(min_max0,columns=['MinMax 0 USIA','MinMax 0 GAJI'])
df_minmax0

MinMax 0 USIA  MinMax 0 GAJI
0       0.607143       0.285714
1       0.000000       0.000000
2       0.440476       0.457143
3       0.285714       0.400000
4       0.464286       0.171429
5       0.285714       0.431746
6       0.392857       0.114286
7       0.750000       0.885714
8       1.000000       1.000000
9       0.178571       0.571429

In [18]:
data = pd.concat([df,df_zscore,df_minmax0,df_minmax10],axis=1)
data


USIA          GAJI  ZSCORE USIA  ZSCORE GAJI  MinMax 0 USIA  \
0  44.000000  58000.000000     0.608581    -0.479776       0.607143   
1  27.000000  48000.000000    -1.608392    -1.418469       0.000000   
2  39.333333  64000.000000     0.000000     0.083439       0.440476   
3  35.000000  62000.000000    -0.565111    -0.104299       0.285714   
4  40.000000  54000.000000     0.086940    -0.855253       0.464286   
5  35.000000  63111.111111    -0.565111     0.000000       0.285714   
6  38.000000  52000.000000    -0.173880    -1.042992       0.392857   
7  48.000000  79000.000000     1.130221     1.491478       0.750000   
8  55.000000  83000.000000     2.043092     1.866955       1.000000   
9  32.000000  68000.000000    -0.956341     0.458916       0.178571   

   MinMax 0 GAJI  MinMax 10 USIA  MinMax 10 GAJI  
0       0.285714        6.464286        3.571429  
1       0.000000        1.000000        1.000000  
2       0.457143        4.964286        5.114286  
3       0.400000        3.571429        4.600000  
4       0.171429        5.178571        2.542857  
5       0.431746        3.571429        4.885714  
6       0.114286        4.535714        2.028571  
7       0.885714        7.750000        8.971429  
8       1.000000       10.000000       10.000000  
9       0.571429        2.607143        6.142857

In [19]:
data.to_excel('hasil_gaji_235314002.xlsx')